# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-18 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_played_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedSummery',
            fields=[
            ],
            options={
                'verbose_name': 'Song Played',
                'verbose_name_plural': 'Songs Played',
                'proxy': True,
            },
            bases=('music.song',),
        ),
    ]
